// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17379
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FluentCodeMetrics.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Calcular Acoplamento Eferente (Ce)")]
    public partial class CalcularAcoplamentoEferenteCeFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EfferentCoupling.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Calcular Acoplamento Eferente (Ce)", @"
Acomplamento Eferente é uma métrica que indica a quantidade
de referências de um tipo para outros.
Entram na contagem: classe base, interfaces implementadas, 
tipos dos variáveis locais, atributos e das propriedades, 
tipos dos parâmetros em métodos e construtores, exceptions.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calcular Acoplamento Eferente para um tipo")]
        [NUnit.Framework.TestCaseAttribute("Samples.EmptyClass", "4", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.OneArgCtor", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.OneArgVoidMethod", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.IntMethod", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.StringArgIntMethod", "3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.SingleProperty", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.SingleField", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.OneException", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.SingleNonAutoProperty", "2", new string[0])]
        public virtual void CalcularAcoplamentoEferenteParaUmTipo(string tipo, string ce, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calcular Acoplamento Eferente para um tipo", exampleTags);
#line 11
 this.ScenarioSetup(scenarioInfo);
#line 12
  testRunner.Given(string.Format("que tenho um {0}", tipo));
#line 13
  testRunner.When("inspeciono seu acoplamento eferente");
#line 14
  testRunner.Then(string.Format("obtenho {0}", ce));
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
